blank_issues_enabled: true
contact_links:
  - name: Join Discord
    url: https://discord.gg/dojocoding
    about: Ask questions and discuss with the Dojo Coding community
  - name: Avalanche Documentation
    url: https://docs.avax.network
    about: Learn more about Avalanche development
  - name: WDK Documentation
    url: https://docs.wallet.tether.io/
    about: Learn more about the Wallet Development Kit